require('dotenv').config();
const express=require('express');
const cors=require('cors');
const mysql=require('mysql2/promise');
const bcrypt=require('bcryptjs');
const jwt=require('jsonwebtoken');
const path=require('path');
const crypto=require('crypto');

const app=express();
app.use(cors()); app.use(express.json());
const PORT=process.env.PORT||3000;
const pool=mysql.createPool({host:process.env.DB_HOST||'localhost',port:process.env.DB_PORT||3306,user:process.env.DB_USER||'root',password:process.env.DB_PASSWORD||'',database:process.env.DB_NAME||'canteen_go',waitForConnections:true,connectionLimit:10,charset:'utf8mb4'});
const JWT_SECRET=process.env.JWT_SECRET||'canteen-go-demo-secret';
const frontend=path.join(__dirname,'..','frontend');
app.use(express.static(frontend));

const q=async(sql,params=[])=>{const [rows]=await pool.execute(sql,params);return rows};
const one=async(sql,params=[])=>{const rows=await q(sql,params);return rows[0]||null};
function token(user){return jwt.sign({id:user.id,role:user.role},JWT_SECRET,{expiresIn:'8h'});}
function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({message:'Vui lòng đăng nhập'});req.user=jwt.verify(h.slice(7),JWT_SECRET);next()}catch(e){return res.status(401).json({message:'Phiên đăng nhập không hợp lệ'})}}
function roles(...rs){return (req,res,next)=>{if(!rs.includes(req.user.role))return res.status(403).json({message:'Bạn không có quyền thực hiện chức năng này'});next()}}
function code(prefix='CG'){return `${prefix}-${Date.now().toString(36).toUpperCase()}${crypto.randomBytes(2).toString('hex').toUpperCase()}`}
async function notify(userId,title,message,type='INFO'){await q('INSERT INTO notifications(user_id,title,message,type) VALUES(?,?,?,?)',[userId,title,message,type])}

app.get('/api/health',async(req,res)=>{try{await q('SELECT 1');res.json({ok:true,service:'Canteen Go API',database:'connected'})}catch(e){res.status(500).json({ok:false,message:e.message})}});

app.post('/api/auth/register',async(req,res)=>{try{let {email,student_code,full_name,phone,password,customer_type}=req.body;if(!email||!full_name||!password)return res.status(400).json({message:'Vui lòng nhập đủ email, họ tên và mật khẩu'});customer_type=customer_type||'STUDENT';
 if(customer_type==='STUDENT'&&!student_code)return res.status(400).json({message:'Sinh viên cần nhập MSSV'});
 const exists=await one('SELECT id FROM users WHERE email=? OR (? IS NOT NULL AND student_code=?)',[email,student_code,student_code]); if(exists)return res.status(409).json({message:'Email hoặc MSSV đã tồn tại'});
 const hash=await bcrypt.hash(password,10); const r=await q('INSERT INTO users(email,student_code,full_name,phone,password_hash,role,customer_type) VALUES(?,?,?,?,?,?,?)',[email,student_code||null,full_name,phone||null,hash,'CUSTOMER',customer_type]);
 await q('INSERT INTO carts(user_id) VALUES(?)',[r.insertId]); const u=await one('SELECT id,email,student_code,full_name,phone,role,customer_type,status,avatar FROM users WHERE id=?',[r.insertId]);res.status(201).json({user:u,token:token(u)})
 }catch(e){res.status(500).json({message:e.message})}});

app.post('/api/auth/login',async(req,res)=>{try{const {email,password,role}=req.body;const u=await one('SELECT * FROM users WHERE email=?',[email]);if(!u||!(await bcrypt.compare(password,u.password_hash)))return res.status(401).json({message:'Sai tài khoản hoặc mật khẩu'});if(u.status==='LOCKED')return res.status(403).json({message:'Tài khoản đang bị khóa'});if(role&&u.role!==role)return res.status(403).json({message:'Tài khoản không thuộc nhóm đăng nhập này'});delete u.password_hash;res.json({user:u,token:token(u)})}catch(e){res.status(500).json({message:e.message})}});
app.get('/api/auth/me',auth,async(req,res)=>{const u=await one('SELECT id,email,student_code,full_name,phone,role,customer_type,status,avatar,created_at FROM users WHERE id=?',[req.user.id]);res.json(u)});
app.put('/api/users/profile',auth,async(req,res)=>{try{const {full_name,phone,student_code}=req.body;await q('UPDATE users SET full_name=?,phone=?,student_code=? WHERE id=?',[full_name,phone||null,student_code||null,req.user.id]);res.json(await one('SELECT id,email,student_code,full_name,phone,role,customer_type,status,avatar FROM users WHERE id=?',[req.user.id]))}catch(e){res.status(400).json({message:e.message})}});
app.put('/api/users/password',auth,async(req,res)=>{try{const {old_password,new_password}=req.body;const u=await one('SELECT password_hash FROM users WHERE id=?',[req.user.id]);if(!(await bcrypt.compare(old_password,u.password_hash)))return res.status(400).json({message:'Mật khẩu hiện tại không đúng'});await q('UPDATE users SET password_hash=? WHERE id=?',[await bcrypt.hash(new_password,10),req.user.id]);res.json({message:'Đổi mật khẩu thành công'})}catch(e){res.status(400).json({message:e.message})}});

app.get('/api/categories',async(req,res)=>res.json(await q("SELECT * FROM categories WHERE status='ACTIVE' ORDER BY id")));
app.get('/api/products',async(req,res)=>{const {search='',category=''}=req.query;let sql="SELECT p.*,c.name category_name,COALESCE(i.quantity,0) stock FROM products p JOIN categories c ON c.id=p.category_id LEFT JOIN inventory i ON i.product_id=p.id WHERE p.status<>'HIDDEN'";const p=[];if(search){sql+=' AND p.name LIKE ?';p.push('%'+search+'%')}if(category){sql+=' AND p.category_id=?';p.push(category)}sql+=' ORDER BY p.id DESC';res.json(await q(sql,p))});
app.get('/api/products/:id',async(req,res)=>{const p=await one("SELECT p.*,c.name category_name,COALESCE(i.quantity,0) stock FROM products p JOIN categories c ON c.id=p.category_id LEFT JOIN inventory i ON i.product_id=p.id WHERE p.id=?",[req.params.id]);if(!p)return res.status(404).json({message:'Không tìm thấy món'});res.json(p)});

app.get('/api/cart',auth,async(req,res)=>{const cart=await one('SELECT id FROM carts WHERE user_id=?',[req.user.id]);if(!cart)return res.json({items:[],total:0});const items=await q('SELECT ci.id,ci.product_id,ci.quantity,p.name,p.price,p.image_url,p.status,COALESCE(i.quantity,0) stock,(ci.quantity*p.price) line_total FROM cart_items ci JOIN products p ON p.id=ci.product_id LEFT JOIN inventory i ON i.product_id=p.id WHERE ci.cart_id=?',[cart.id]);res.json({items,total:items.reduce((s,x)=>s+Number(x.line_total),0)})});
app.post('/api/cart/items',auth,async(req,res)=>{try{const {product_id,quantity=1}=req.body;const p=await one('SELECT p.*,COALESCE(i.quantity,0) stock FROM products p LEFT JOIN inventory i ON i.product_id=p.id WHERE p.id=?',[product_id]);if(!p||p.status!=='AVAILABLE')return res.status(400).json({message:'Món không còn bán'});if(quantity<1||quantity>p.stock)return res.status(400).json({message:`Chỉ còn ${p.stock} phần`});const cart=await one('SELECT id FROM carts WHERE user_id=?',[req.user.id]);await q('INSERT INTO cart_items(cart_id,product_id,quantity) VALUES(?,?,?) ON DUPLICATE KEY UPDATE quantity=LEAST(quantity+VALUES(quantity),?)',[cart.id,product_id,quantity,p.stock]);res.json({message:'Đã thêm vào giỏ'})}catch(e){res.status(400).json({message:e.message})}});
app.put('/api/cart/items/:id',auth,async(req,res)=>{try{const {quantity}=req.body;const row=await one('SELECT ci.*,COALESCE(i.quantity,0) stock FROM cart_items ci LEFT JOIN inventory i ON i.product_id=ci.product_id JOIN carts c ON c.id=ci.cart_id WHERE ci.id=? AND c.user_id=?',[req.params.id,req.user.id]);if(!row)return res.status(404).json({message:'Không tìm thấy món trong giỏ'});if(quantity<=0){await q('DELETE FROM cart_items WHERE id=?',[req.params.id])}else if(quantity>row.stock)return res.status(400).json({message:`Chỉ còn ${row.stock} phần`});else await q('UPDATE cart_items SET quantity=? WHERE id=?',[quantity,req.params.id]);res.json({message:'Đã cập nhật giỏ hàng'})}catch(e){res.status(400).json({message:e.message})}});
app.delete('/api/cart/items/:id',auth,async(req,res)=>{await q('DELETE ci FROM cart_items ci JOIN carts c ON c.id=ci.cart_id WHERE ci.id=? AND c.user_id=?',[req.params.id,req.user.id]);res.json({message:'Đã xóa món'})});

app.get('/api/pickup-slots',auth,async(req,res)=>{await q("UPDATE pickup_slots SET status=IF(booked_count>=capacity,'FULL','OPEN')");res.json(await q("SELECT *,DATE_FORMAT(start_time,'%H:%i') start_label,DATE_FORMAT(end_time,'%H:%i') end_label FROM pickup_slots WHERE slot_date>=CURDATE() AND status<>'CLOSED' ORDER BY slot_date,start_time"))});

app.post('/api/orders',auth,async(req,res)=>{const conn=await pool.getConnection();try{await conn.beginTransaction();const {pickup_slot_id}=req.body;const cart=await conn.query('SELECT id FROM carts WHERE user_id=?',[req.user.id]);const cartId=cart[0][0]?.id;if(!cartId)throw new Error('Giỏ hàng trống');const [items]=await conn.query('SELECT ci.*,p.name,p.price,p.status,COALESCE(i.quantity,0) stock FROM cart_items ci JOIN products p ON p.id=ci.product_id LEFT JOIN inventory i ON i.product_id=p.id WHERE ci.cart_id=? FOR UPDATE',[cartId]);if(!items.length)throw new Error('Giỏ hàng trống');const slot=(await conn.query('SELECT * FROM pickup_slots WHERE id=? FOR UPDATE',[pickup_slot_id]))[0][0];if(!slot||slot.status!=='OPEN'||slot.booked_count>=slot.capacity)throw new Error('Khung giờ nhận món không còn khả dụng');for(const x of items){if(x.status!=='AVAILABLE'||x.quantity>x.stock)throw new Error(`Món ${x.name} không đủ số lượng`)}const total=items.reduce((s,x)=>s+Number(x.price)*x.quantity,0);const oc=code();const [r]=await conn.query('INSERT INTO orders(order_code,user_id,pickup_slot_id,pickup_date,pickup_time,total_amount,status) VALUES(?,?,?,?,?,?,?)',[oc,req.user.id,pickup_slot_id,slot.slot_date,`${slot.start_time}-${slot.end_time}`,total,'PENDING_PAYMENT']);for(const x of items){await conn.query('INSERT INTO order_items(order_id,product_id,product_name,unit_price,quantity,line_total) VALUES(?,?,?,?,?,?)',[r.insertId,x.product_id,x.name,x.price,x.quantity,Number(x.price)*x.quantity]);await conn.query('UPDATE inventory SET quantity=quantity-? WHERE product_id=?',[x.quantity,x.product_id])}await conn.query('UPDATE pickup_slots SET booked_count=booked_count+1 WHERE id=?',[pickup_slot_id]);await conn.query('DELETE FROM cart_items WHERE cart_id=?',[cartId]);await conn.query('INSERT INTO payments(order_id,amount,method,status) VALUES(?,?,?,?)',[r.insertId,total,'EWALLET_SIMULATED','PENDING']);await conn.query('INSERT INTO order_status_history(order_id,status,note,changed_by) VALUES(?,?,?,?)',[r.insertId,'PENDING_PAYMENT','Tạo đơn chờ thanh toán',req.user.id]);await conn.commit();await notify(req.user.id,'Đặt món thành công',`Đơn ${oc} đã được tạo, vui lòng thanh toán.`,'ORDER');res.status(201).json(await one('SELECT * FROM orders WHERE id=?',[r.insertId]))}catch(e){await conn.rollback();res.status(400).json({message:e.message})}finally{conn.release()}});

app.get('/api/orders/my',auth,async(req,res)=>{const orders=await q('SELECT o.*,p.status payment_status,i.invoice_code FROM orders o LEFT JOIN payments p ON p.order_id=o.id LEFT JOIN invoices i ON i.order_id=o.id WHERE o.user_id=? ORDER BY o.id DESC',[req.user.id]);for(const o of orders)o.items=await q('SELECT * FROM order_items WHERE order_id=?',[o.id]);res.json(orders)});
app.get('/api/orders/:id',auth,async(req,res)=>{const o=await one('SELECT o.*,u.full_name,u.phone,p.status payment_status,p.method,p.transaction_code,i.invoice_code FROM orders o JOIN users u ON u.id=o.user_id LEFT JOIN payments p ON p.order_id=o.id LEFT JOIN invoices i ON i.order_id=o.id WHERE o.id=?',[req.params.id]);if(!o)return res.status(404).json({message:'Không tìm thấy đơn'});if(req.user.role==='CUSTOMER'&&o.user_id!==req.user.id)return res.status(403).json({message:'Không có quyền'});o.items=await q('SELECT * FROM order_items WHERE order_id=?',[o.id]);o.history=await q('SELECT osh.*,u.full_name changed_by_name FROM order_status_history osh LEFT JOIN users u ON u.id=osh.changed_by WHERE osh.order_id=? ORDER BY osh.id',[o.id]);res.json(o)});
app.post('/api/orders/:id/cancel',auth,async(req,res)=>{const conn=await pool.getConnection();try{await conn.beginTransaction();const o=(await conn.query('SELECT * FROM orders WHERE id=? AND user_id=? FOR UPDATE',[req.params.id,req.user.id]))[0][0];if(!o)throw new Error('Đơn không tồn tại');if(o.status!=='PENDING_PAYMENT'&&o.status!=='PENDING')throw new Error('Đơn đã được xử lý, không thể hủy');if(Date.now()-new Date(o.placed_at).getTime()>5*60*1000)throw new Error('Đơn đã quá 5 phút, không thể hủy');const [its]=await conn.query('SELECT * FROM order_items WHERE order_id=?',[o.id]);for(const x of its)await conn.query('UPDATE inventory SET quantity=quantity+? WHERE product_id=?',[x.quantity,x.product_id]);if(o.pickup_slot_id)await conn.query('UPDATE pickup_slots SET booked_count=GREATEST(booked_count-1,0) WHERE id=?',[o.pickup_slot_id]);await conn.query("UPDATE orders SET status='CANCELLED' WHERE id=?",[o.id]);await conn.query('INSERT INTO order_status_history(order_id,status,note,changed_by) VALUES(?,?,?,?)',[o.id,'CANCELLED','Khách hàng hủy đơn',req.user.id]);await conn.commit();res.json({message:'Đã hủy đơn'})}catch(e){await conn.rollback();res.status(400).json({message:e.message})}finally{conn.release()}});

app.post('/api/payments/:orderId',auth,async(req,res)=>{const conn=await pool.getConnection();try{await conn.beginTransaction();const o=(await conn.query('SELECT * FROM orders WHERE id=? AND user_id=? FOR UPDATE',[req.params.orderId,req.user.id]))[0][0];if(!o)throw new Error('Đơn không tồn tại');if(o.status!=='PENDING_PAYMENT')throw new Error('Đơn không ở trạng thái chờ thanh toán');const {method='EWALLET_SIMULATED',result='SUCCESS'}=req.body;const success=result==='SUCCESS';const tx=code('TX');await conn.query('UPDATE payments SET method=?,status=?,transaction_code=?,failure_reason=?,paid_at=? WHERE order_id=?',[method,success?'SUCCESS':'FAILED',tx,success?null:'Thanh toán mô phỏng thất bại',success?new Date():null,o.id]);if(success){await conn.query("UPDATE orders SET status='PENDING' WHERE id=?",[o.id]);const inv=code('INV');await conn.query('INSERT INTO invoices(invoice_code,order_id) VALUES(?,?)',[inv,o.id]);await conn.query('INSERT INTO order_status_history(order_id,status,note,changed_by) VALUES(?,?,?,?)',[o.id,'PENDING','Thanh toán thành công - chờ nhân viên xác nhận',req.user.id]);await conn.commit();await notify(req.user.id,'Thanh toán thành công',`Đơn ${o.order_code} đã thanh toán. Mã hóa đơn ${inv}.`,'PAYMENT');res.json({success:true,invoice_code:inv,transaction_code:tx})}else{await conn.commit();await notify(req.user.id,'Thanh toán thất bại',`Đơn ${o.order_code}: thanh toán mô phỏng thất bại. Bạn có thể thử lại.`,'PAYMENT');res.json({success:false,message:'Thanh toán thất bại',transaction_code:tx})}}catch(e){await conn.rollback();res.status(400).json({message:e.message})}finally{conn.release()}});

app.get('/api/notifications',auth,async(req,res)=>res.json(await q('SELECT * FROM notifications WHERE user_id=? ORDER BY id DESC LIMIT 30',[req.user.id])));
app.put('/api/notifications/:id/read',auth,async(req,res)=>{await q('UPDATE notifications SET is_read=1 WHERE id=? AND user_id=?',[req.params.id,req.user.id]);res.json({ok:true})});

// STAFF
app.get('/api/staff/orders',auth,roles('STAFF','ADMIN'),async(req,res)=>{const {status='',search=''}=req.query;let sql='SELECT o.*,u.full_name,u.phone,p.status payment_status FROM orders o JOIN users u ON u.id=o.user_id LEFT JOIN payments p ON p.order_id=o.id WHERE 1=1';const ps=[];if(status){sql+=' AND o.status=?';ps.push(status)}if(search){sql+=' AND (o.order_code LIKE ? OR u.full_name LIKE ?)';ps.push('%'+search+'%','%'+search+'%')}sql+=' ORDER BY o.id DESC';res.json(await q(sql,ps))});
app.patch('/api/staff/orders/:id/status',auth,roles('STAFF','ADMIN'),async(req,res)=>{try{const {status,rejection_reason}=req.body;const allowed=['CONFIRMED','PREPARING','READY','COMPLETED','REJECTED'];if(!allowed.includes(status))return res.status(400).json({message:'Trạng thái không hợp lệ'});const o=await one('SELECT * FROM orders WHERE id=?',[req.params.id]);if(!o)return res.status(404).json({message:'Không tìm thấy đơn'});if(status==='REJECTED'&&o.status!=='PENDING')return res.status(400).json({message:'Chỉ có thể từ chối đơn đang chờ xử lý'});await q('UPDATE orders SET status=?,rejection_reason=?,completed_at=? WHERE id=?',[status,rejection_reason||null,status==='COMPLETED'?new Date():null,o.id]);await q('INSERT INTO order_status_history(order_id,status,note,changed_by) VALUES(?,?,?,?)',[o.id,status,rejection_reason||null,req.user.id]);if(status==='REJECTED'||status==='CANCELLED'){const its=await q('SELECT * FROM order_items WHERE order_id=?',[o.id]);for(const x of its)await q('UPDATE inventory SET quantity=quantity+? WHERE product_id=?',[x.quantity,x.product_id])}await notify(o.user_id,'Cập nhật đơn hàng',`Đơn ${o.order_code} chuyển sang trạng thái ${status}.`,'ORDER');res.json({message:'Đã cập nhật trạng thái'})}catch(e){res.status(400).json({message:e.message})}});

// ADMIN
app.get('/api/admin/users',auth,roles('ADMIN'),async(req,res)=>res.json(await q('SELECT id,email,student_code,full_name,phone,role,customer_type,status,created_at FROM users ORDER BY id DESC')));
app.post('/api/admin/users',auth,roles('ADMIN'),async(req,res)=>{try{const {email,full_name,phone,password='123456',role='CUSTOMER',customer_type='STUDENT',student_code}=req.body;const hash=await bcrypt.hash(password,10);const r=await q('INSERT INTO users(email,student_code,full_name,phone,password_hash,role,customer_type) VALUES(?,?,?,?,?,?,?)',[email,student_code||null,full_name,phone||null,hash,role,role==='CUSTOMER'?customer_type:null]);if(role==='CUSTOMER')await q('INSERT INTO carts(user_id) VALUES(?)',[r.insertId]);res.json({message:'Đã tạo tài khoản'})}catch(e){res.status(400).json({message:e.message})}});
app.patch('/api/admin/users/:id/status',auth,roles('ADMIN'),async(req,res)=>{await q('UPDATE users SET status=? WHERE id=?',[req.body.status,req.params.id]);res.json({message:'Đã cập nhật trạng thái tài khoản'})});
app.delete('/api/admin/users/:id',auth,roles('ADMIN'),async(req,res)=>{await q('DELETE FROM users WHERE id=? AND role<>\'ADMIN\'',[req.params.id]);res.json({message:'Đã xóa tài khoản'})});
app.post('/api/admin/categories',auth,roles('ADMIN'),async(req,res)=>{try{await q('INSERT INTO categories(name,icon,description) VALUES(?,?,?)',[req.body.name,req.body.icon||'🍽️',req.body.description||'']);res.json({message:'Đã thêm danh mục'})}catch(e){res.status(400).json({message:e.message})}});
app.put('/api/admin/categories/:id',auth,roles('ADMIN'),async(req,res)=>{await q('UPDATE categories SET name=?,icon=?,description=?,status=? WHERE id=?',[req.body.name,req.body.icon,req.body.description,req.body.status||'ACTIVE',req.params.id]);res.json({message:'Đã cập nhật danh mục'})});
app.delete('/api/admin/categories/:id',auth,roles('ADMIN'),async(req,res)=>{await q("UPDATE categories SET status='INACTIVE' WHERE id=?",[req.params.id]);res.json({message:'Đã ẩn danh mục'})});
app.post('/api/admin/products',auth,roles('ADMIN'),async(req,res)=>{try{const {category_id,name,description,price,image_url,status='AVAILABLE',stock=0}=req.body;const r=await q('INSERT INTO products(category_id,name,description,price,image_url,status) VALUES(?,?,?,?,?,?)',[category_id,name,description||'',price,image_url||'assets/food-rice.svg',status]);await q('INSERT INTO inventory(product_id,quantity,unit,supplier,expiry_date) VALUES(?,?,?,?,?)',[r.insertId,stock,'suất','Nhà cung cấp VWA',req.body.expiry_date||null]);res.json({message:'Đã thêm món'})}catch(e){res.status(400).json({message:e.message})}});
app.put('/api/admin/products/:id',auth,roles('ADMIN'),async(req,res)=>{try{const {category_id,name,description,price,image_url,status}=req.body;await q('UPDATE products SET category_id=?,name=?,description=?,price=?,image_url=?,status=? WHERE id=?',[category_id,name,description,price,image_url,status,req.params.id]);if(req.body.stock!==undefined)await q('UPDATE inventory SET quantity=?,supplier=?,expiry_date=? WHERE product_id=?',[req.body.stock,req.body.supplier||'Nhà cung cấp VWA',req.body.expiry_date||null,req.params.id]);res.json({message:'Đã cập nhật món'})}catch(e){res.status(400).json({message:e.message})}});
app.delete('/api/admin/products/:id',auth,roles('ADMIN'),async(req,res)=>{await q("UPDATE products SET status='HIDDEN' WHERE id=?",[req.params.id]);res.json({message:'Đã ẩn món'})});
app.get('/api/admin/inventory',auth,roles('ADMIN'),async(req,res)=>res.json(await q('SELECT i.*,p.name,p.price,p.status FROM inventory i JOIN products p ON p.id=i.product_id ORDER BY i.id DESC')));
app.put('/api/admin/inventory/:id',auth,roles('ADMIN'),async(req,res)=>{await q('UPDATE inventory SET quantity=?,unit=?,supplier=?,expiry_date=? WHERE id=?',[req.body.quantity,req.body.unit||'suất',req.body.supplier||'',req.body.expiry_date||null,req.params.id]);res.json({message:'Đã cập nhật kho'})});
app.get('/api/admin/reviews',auth,roles('ADMIN'),async(req,res)=>res.json(await q('SELECT r.*,u.full_name,p.name product_name,o.order_code FROM reviews r JOIN users u ON u.id=r.user_id JOIN products p ON p.id=r.product_id JOIN orders o ON o.id=r.order_id ORDER BY r.id DESC')));
app.delete('/api/admin/reviews/:id',auth,roles('ADMIN'),async(req,res)=>{await q('DELETE FROM reviews WHERE id=?',[req.params.id]);res.json({message:'Đã xóa đánh giá'})});

app.post('/api/reviews',auth,async(req,res)=>{try{const {order_id,product_id,rating,comment}=req.body;const o=await one("SELECT id FROM orders WHERE id=? AND user_id=? AND status='COMPLETED'",[order_id,req.user.id]);if(!o)return res.status(400).json({message:'Chỉ đánh giá đơn đã hoàn tất'});await q('INSERT INTO reviews(user_id,order_id,product_id,rating,comment) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE rating=VALUES(rating),comment=VALUES(comment)',[req.user.id,order_id,product_id,rating,comment||'']);res.json({message:'Đã gửi đánh giá'})}catch(e){res.status(400).json({message:e.message})}});
app.get('/api/reviews/my',auth,async(req,res)=>res.json(await q('SELECT r.*,p.name product_name,o.order_code FROM reviews r JOIN products p ON p.id=r.product_id JOIN orders o ON o.id=r.order_id WHERE r.user_id=? ORDER BY r.id DESC',[req.user.id])));

app.get('/api/admin/reports',auth,roles('ADMIN'),async(req,res)=>{const [summary]=await Promise.all([q("SELECT COUNT(*) orders,COALESCE(SUM(CASE WHEN status NOT IN ('CANCELLED','REJECTED','PENDING_PAYMENT') THEN total_amount ELSE 0 END),0) revenue,COUNT(DISTINCT user_id) customers FROM orders")]);const revenue=await q("SELECT DATE(placed_at) day,SUM(total_amount) revenue,COUNT(*) orders FROM orders WHERE status IN ('PENDING','CONFIRMED','PREPARING','READY','COMPLETED') AND placed_at>=DATE_SUB(CURDATE(),INTERVAL 6 DAY) GROUP BY DATE(placed_at) ORDER BY day");const statuses=await q('SELECT status,COUNT(*) count FROM orders GROUP BY status');const best=await q("SELECT oi.product_id,oi.product_name,SUM(oi.quantity) quantity,SUM(oi.line_total) revenue FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE o.status='COMPLETED' GROUP BY oi.product_id,oi.product_name ORDER BY quantity DESC LIMIT 5");const stock=await one('SELECT COUNT(*) total_products,SUM(quantity) total_stock,SUM(quantity=0) sold_out FROM inventory');res.json({summary:summary[0],revenue,statuses,best,stock})});

// Serve role pages as SPA-friendly fallback.
app.get('*',(req,res)=>res.sendFile(path.join(frontend,'index.html')));

async function seed(){
 try{
  await q('SELECT 1');
  const users=[
   ['student@vwa.edu.vn','SV001','Nguyễn Minh Anh','0900000001','123456','CUSTOMER','STUDENT'],
   ['teacher@vwa.edu.vn','GV001','Giảng viên VWA','0900000002','123456','CUSTOMER','TEACHER'],
   ['staff@canteen.vn',null,'Nhân viên Canteen','0900000003','123456','STAFF',null],
   ['admin@canteen.vn',null,'Quản trị viên','0900000004','123456','ADMIN',null]
  ];
  for(const u of users){const exists=await one('SELECT id FROM users WHERE email=?',[u[0]]);if(!exists){const h=await bcrypt.hash(u[4],10);const r=await q('INSERT INTO users(email,student_code,full_name,phone,password_hash,role,customer_type) VALUES(?,?,?,?,?,?,?)',[u[0],u[1],u[2],u[3],h,u[5],u[6]]);if(u[5]==='CUSTOMER')await q('INSERT INTO carts(user_id) VALUES(?)',[r.insertId]);}}
  console.log('Seed accounts ready.');
 }catch(e){console.error('Seed skipped:',e.message)}
}
app.listen(PORT,async()=>{console.log(`Canteen Go running: http://localhost:${PORT}`);await seed()});
